@api_host = http://localhost:5128

GET {{api_host}}/health/
Accept: application/json

###

POST {{api_host}}/api/auth/register
Accept: application/json
Content-Type: application/json
{
  "username": "loyd17",
  "email": "example@gmail.com",
  "password": "Test@1234"
}

###

POST {{api_host}}/api/auth/login
Content-Type: application/json
{
  "login": "example@gmail.com",
  "password": "Test@1234"
}

###

POST {{api_host}}/api/auth/refresh
Content-Type: application/json
{
  "guid": "CA3ADCCB-529E-4946-9280-760F2F9D9A2B",
  "refreshtoken": "iEIao7qz5bMNSY/MHK8UxVCzWzhlFkN4H94eqsXXuWk="
}

###